// ==========================================
// FoodBridge — Mock Data Layer
// ==========================================

export const MOCK_USERS = [
  {
    id: 'usr_001',
    name: 'Rajesh Kumar',
    email: 'rajesh@restaurant.com',
    password: 'password123',
    role: 'donor',
    type: 'Restaurant',
    organization: 'Spice Garden Restaurant',
    phone: '+91 98765 43210',
    address: '123 MG Road, Bangalore',
    avatar: null,
    lat: 12.9716,
    lng: 77.5946,
    verified: true,
    badges: ['First Donation', 'Regular Donor', '100 Meals'],
    totalDonations: 47,
    mealsServed: 2350,
    joinedAt: '2024-08-15',
  },
  {
    id: 'usr_002',
    name: 'Ananya Sharma',
    email: 'ananya@ngo.org',
    password: 'password123',
    role: 'ngo',
    type: 'NGO',
    organization: 'Feeding India Foundation',
    phone: '+91 87654 32109',
    address: '456 Relief Road, Mumbai',
    avatar: null,
    lat: 19.076,
    lng: 72.8777,
    verified: true,
    badges: ['Verified NGO', 'Top Collector'],
    totalCollections: 123,
    peopleServed: 8900,
    joinedAt: '2024-06-20',
  },
  {
    id: 'usr_003',
    name: 'Vikram Patel',
    email: 'vikram@volunteer.com',
    password: 'password123',
    role: 'volunteer',
    type: 'Volunteer',
    organization: null,
    phone: '+91 76543 21098',
    address: '789 Volunteer Lane, Delhi',
    avatar: null,
    lat: 28.6139,
    lng: 77.209,
    verified: true,
    badges: ['Speed Runner', 'Night Owl'],
    totalDeliveries: 34,
    hoursVolunteered: 120,
    joinedAt: '2024-09-01',
  },
  {
    id: 'usr_004',
    name: 'Admin User',
    email: 'admin@foodbridge.org',
    password: 'admin123',
    role: 'admin',
    type: 'Admin',
    organization: 'FoodBridge',
    phone: '+91 99999 00000',
    address: 'FoodBridge HQ',
    avatar: null,
    lat: 12.9716,
    lng: 77.5946,
    verified: true,
    badges: [],
    joinedAt: '2024-01-01',
  },
];

export const MOCK_DONATIONS = [
  {
    id: 'don_001',
    donorId: 'usr_001',
    donorName: 'Spice Garden Restaurant',
    foodName: 'Vegetable Biryani',
    quantity: '15 kg',
    servings: 50,
    foodType: 'veg',
    expiryTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    pickupAddress: '123 MG Road, Bangalore',
    lat: 12.9716,
    lng: 77.5946,
    image: '/food/biryani.jpg',
    instructions: 'Please bring containers. Best served warm.',
    status: 'available',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    claimedBy: null,
    volunteerId: null,
  },
  {
    id: 'don_002',
    donorId: 'usr_001',
    donorName: 'Spice Garden Restaurant',
    foodName: 'Paneer Tikka & Naan',
    quantity: '8 kg',
    servings: 30,
    foodType: 'veg',
    expiryTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    pickupAddress: '123 MG Road, Bangalore',
    lat: 12.9716,
    lng: 77.5946,
    image: '/food/paneer.jpg',
    instructions: 'Includes 20 pieces of naan bread.',
    status: 'requested',
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    claimedBy: 'usr_002',
    volunteerId: null,
  },
  {
    id: 'don_003',
    donorId: 'usr_001',
    donorName: 'Grand Hotel Bangalore',
    foodName: 'Mixed Rice & Dal',
    quantity: '25 kg',
    servings: 100,
    foodType: 'veg',
    expiryTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    pickupAddress: '45 Brigade Road, Bangalore',
    lat: 12.975,
    lng: 77.607,
    image: '/food/dal-rice.jpg',
    instructions: 'Freshly prepared. Rice and dal in separate containers.',
    status: 'available',
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    claimedBy: null,
    volunteerId: null,
  },
  {
    id: 'don_004',
    donorId: 'usr_001',
    donorName: 'Wedding Caterers',
    foodName: 'Assorted Sweets & Snacks',
    quantity: '10 kg',
    servings: 80,
    foodType: 'veg',
    expiryTime: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    pickupAddress: '78 Jubilee Hills, Hyderabad',
    lat: 17.432,
    lng: 78.409,
    image: '/food/sweets.jpg',
    instructions: 'Wedding leftovers. All items packed hygienically.',
    status: 'available',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    claimedBy: null,
    volunteerId: null,
  },
  {
    id: 'don_005',
    donorId: 'usr_001',
    donorName: 'Fresh Kitchen',
    foodName: 'Chicken Curry & Rice',
    quantity: '12 kg',
    servings: 40,
    foodType: 'non-veg',
    expiryTime: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    pickupAddress: '320 Park Street, Kolkata',
    lat: 22.553,
    lng: 88.345,
    image: '/food/chicken.jpg',
    instructions: 'Non-vegetarian. Keep refrigerated if not distributed immediately.',
    status: 'accepted',
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    claimedBy: 'usr_002',
    volunteerId: 'usr_003',
  },
  {
    id: 'don_006',
    donorId: 'usr_001',
    donorName: 'Cafe Mocha',
    foodName: 'Sandwiches & Pastries',
    quantity: '5 kg',
    servings: 20,
    foodType: 'veg',
    expiryTime: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
    pickupAddress: '12 Connaught Place, Delhi',
    lat: 28.632,
    lng: 77.221,
    image: '/food/sandwich.jpg',
    instructions: 'Day-end leftovers. Still fresh.',
    status: 'available',
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    claimedBy: null,
    volunteerId: null,
  },
];

export const MOCK_NGOS = [
  {
    id: 'ngo_001',
    name: 'Feeding India Foundation',
    email: 'contact@feedingindia.org',
    phone: '+91 87654 32109',
    address: '456 Relief Road, Mumbai',
    lat: 19.076,
    lng: 72.8777,
    description: 'Fighting hunger across India by rescuing surplus food and distributing it to those in need.',
    verified: true,
    peopleServed: 8900,
    activeSince: '2018',
    logo: null,
  },
  {
    id: 'ngo_002',
    name: 'Robin Hood Army',
    email: 'hello@robinhoodarmy.com',
    phone: '+91 76543 21098',
    address: '789 Volunteer Lane, Delhi',
    lat: 28.6139,
    lng: 77.209,
    description: 'A zero-fund volunteer organization fighting hunger and food wastage.',
    verified: true,
    peopleServed: 15000,
    activeSince: '2014',
    logo: null,
  },
  {
    id: 'ngo_003',
    name: 'Akshaya Patra',
    email: 'info@akshayapatra.org',
    phone: '+91 65432 10987',
    address: '101 Temple Road, Bangalore',
    lat: 12.983,
    lng: 77.587,
    description: 'Serving mid-day meals to school children and distributing food to underprivileged communities.',
    verified: true,
    peopleServed: 25000,
    activeSince: '2000',
    logo: null,
  },
  {
    id: 'ngo_004',
    name: 'No Food Waste',
    email: 'info@nofoodwaste.org',
    phone: '+91 54321 09876',
    address: '202 Marina Road, Chennai',
    lat: 13.0827,
    lng: 80.2707,
    description: 'Connecting surplus food from functions and restaurants with people in need.',
    verified: false,
    peopleServed: 5000,
    activeSince: '2015',
    logo: null,
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'notif_001',
    userId: 'usr_002',
    type: 'new_donation',
    title: 'New Donation Nearby!',
    message: 'Spice Garden Restaurant just posted 50 servings of Vegetable Biryani, 2.3 km from you.',
    read: false,
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif_002',
    userId: 'usr_001',
    type: 'pickup_accepted',
    title: 'Pickup Request Accepted',
    message: 'Feeding India Foundation accepted your donation of Paneer Tikka & Naan.',
    read: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif_003',
    userId: 'usr_003',
    type: 'delivery_assigned',
    title: 'New Delivery Assignment',
    message: 'You have been assigned to deliver Chicken Curry & Rice from Fresh Kitchen to Feeding India Foundation.',
    read: true,
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
];

export const PLATFORM_STATS = {
  totalMealsSaved: 125430,
  totalDonations: 8756,
  activeNGOs: 342,
  volunteersActive: 1205,
  kgFoodSaved: 45670,
  citiesCovered: 28,
  peopleFed: 98200,
  co2Prevented: 12450,
};

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Priya Menon',
    role: 'Restaurant Owner',
    text: 'FoodBridge transformed how we handle surplus food. Instead of throwing away perfectly good meals, we now feed dozens of people every week. The platform is incredibly easy to use.',
    rating: 5,
  },
  {
    id: 2,
    name: 'Arjun Reddy',
    role: 'NGO Coordinator',
    text: 'The real-time notifications help us respond to food donations within minutes. We\'ve tripled our food collection since joining FoodBridge.',
    rating: 5,
  },
  {
    id: 3,
    name: 'Meera Joshi',
    role: 'Volunteer',
    text: 'I love being a FoodBridge volunteer. The app makes it so easy to find pickups near me. I\'ve delivered over 200 meals in just 3 months!',
    rating: 5,
  },
];

export const BADGES = [
  { id: 'first_donation', name: 'First Donation', icon: '🌱', description: 'Made your first food donation' },
  { id: 'regular_donor', name: 'Regular Donor', icon: '⭐', description: 'Donated food 10+ times' },
  { id: '100_meals', name: '100 Meals', icon: '🍽️', description: 'Helped serve 100+ meals' },
  { id: '500_meals', name: '500 Meals', icon: '🏆', description: 'Helped serve 500+ meals' },
  { id: 'speed_runner', name: 'Speed Runner', icon: '⚡', description: 'Completed 5 deliveries under 30 min' },
  { id: 'night_owl', name: 'Night Owl', icon: '🦉', description: 'Made 10+ deliveries after 8 PM' },
  { id: 'verified_ngo', name: 'Verified NGO', icon: '✅', description: 'Platform-verified organization' },
  { id: 'top_collector', name: 'Top Collector', icon: '🥇', description: 'Top 5% in food collection' },
  { id: 'community_hero', name: 'Community Hero', icon: '🦸', description: '1000+ meals contributed' },
  { id: 'zero_waste', name: 'Zero Waste Champion', icon: '♻️', description: 'Zero expired donations' },
];
